"""Add Player and TeamPlayer models

Revision ID: 04c77729c223
Revises: 8e73729359e2
Create Date: 2025-10-05 13:39:53.087438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c77729c223'
down_revision: Union[str, Sequence[str], None] = '8e73729359e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('known_as', sa.String(length=80), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('batting_style', sa.String(length=8), nullable=True),
    sa.Column('bowling_style', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_public_id'), 'players', ['public_id'], unique=True)
    op.create_table('team_player',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('role_hint_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_player')
    op.drop_index(op.f('ix_players_public_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
