"""Add MatchPlayer, Innings, and Delivery models

Revision ID: 0d05fadc84f7
Revises: 71c5d8b24323
Create Date: 2025-10-05 13:58:37.679060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d05fadc84f7'
down_revision: Union[str, Sequence[str], None] = '71c5d8b24323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('innings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('batting_team_id', sa.BigInteger(), nullable=False),
    sa.Column('bowling_team_id', sa.BigInteger(), nullable=False),
    sa.Column('seq_number', sa.Integer(), nullable=False),
    sa.Column('follow_on', sa.Boolean(), nullable=False),
    sa.Column('declared', sa.Boolean(), nullable=False),
    sa.Column('forfeited', sa.Boolean(), nullable=False),
    sa.Column('target_runs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batting_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['bowling_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'seq_number', name='uq_innings_match_seq'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('match_player',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('is_playing_xi', sa.Boolean(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_wicketkeeper', sa.Boolean(), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_match_player')
    )
    op.create_table('delivery',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('innings_id', sa.BigInteger(), nullable=False),
    sa.Column('striker_id', sa.BigInteger(), nullable=False),
    sa.Column('non_striker_id', sa.BigInteger(), nullable=False),
    sa.Column('bowler_id', sa.BigInteger(), nullable=False),
    sa.Column('over_number', sa.Integer(), nullable=False),
    sa.Column('ball_in_over', sa.Integer(), nullable=False),
    sa.Column('is_legal_delivery', sa.Boolean(), nullable=False),
    sa.Column('ts_utc', sa.String(length=32), nullable=False),
    sa.Column('runs_batter', sa.Integer(), nullable=False),
    sa.Column('runs_extras', sa.Integer(), nullable=False),
    sa.Column('extra_type', sa.String(length=16), nullable=True),
    sa.Column('is_four', sa.Boolean(), nullable=False),
    sa.Column('is_six', sa.Boolean(), nullable=False),
    sa.Column('wicket_type', sa.String(length=16), nullable=True),
    sa.Column('out_player_id', sa.BigInteger(), nullable=True),
    sa.Column('fielder_id', sa.BigInteger(), nullable=True),
    sa.Column('wagon_x', sa.Float(), nullable=True),
    sa.Column('wagon_y', sa.Float(), nullable=True),
    sa.Column('pitch_x', sa.Float(), nullable=True),
    sa.Column('pitch_y', sa.Float(), nullable=True),
    sa.Column('commentary_text', sa.Text(), nullable=True),
    sa.Column('replaces_delivery_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bowler_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['fielder_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['innings_id'], ['innings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['non_striker_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['out_player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['replaces_delivery_id'], ['delivery.id'], ),
    sa.ForeignKeyConstraint(['striker_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('innings_id', 'over_number', 'ball_in_over', 'replaces_delivery_id', name='uq_delivery_innings_ball'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index('idx_delivery_batters', 'delivery', ['striker_id', 'non_striker_id'], unique=False)
    op.create_index('idx_delivery_bowler', 'delivery', ['bowler_id'], unique=False)
    op.create_index('idx_delivery_innings_over', 'delivery', ['innings_id', 'over_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_delivery_innings_over', table_name='delivery')
    op.drop_index('idx_delivery_bowler', table_name='delivery')
    op.drop_index('idx_delivery_batters', table_name='delivery')
    op.drop_table('delivery')
    op.drop_table('match_player')
    op.drop_table('innings')
    # ### end Alembic commands ###
