"""Add Tournament model

Revision ID: 37560f2572d3
Revises: c609c31fee43
Create Date: 2025-10-05 13:45:34.364658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37560f2572d3'
down_revision: Union[str, Sequence[str], None] = 'c609c31fee43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('season_label', sa.String(length=32), nullable=True),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('points_system', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'season_label', name='uq_tournament_name_season')
    )
    op.create_index(op.f('ix_tournaments_public_id'), 'tournaments', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournaments_public_id'), table_name='tournaments')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
