"""Add Match, MatchTeam, and MatchToss models

Revision ID: 71c5d8b24323
Revises: 37560f2572d3
Create Date: 2025-10-05 13:51:21.117832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c5d8b24323'
down_revision: Union[str, Sequence[str], None] = '37560f2572d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('local_tz', sa.String(length=64), nullable=True),
    sa.Column('overs_limit', sa.Integer(), nullable=True),
    sa.Column('balls_per_over', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_public_id'), 'matches', ['public_id'], unique=True)
    op.create_table('match_team',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'team_id', name='uq_match_team')
    )
    op.create_table('match_toss',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('won_by_team_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['won_by_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('match_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_toss')
    op.drop_table('match_team')
    op.drop_index(op.f('ix_matches_public_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
