"""Add country_code to team model

Revision ID: 8e73729359e2
Revises: 596aee59bda4
Create Date: 2025-10-05 13:34:27.559417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e73729359e2'
down_revision: Union[str, Sequence[str], None] = '596aee59bda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('country_code', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'country_code')
    # ### end Alembic commands ###
