"""Add Venue model

Revision ID: c609c31fee43
Revises: 04c77729c223
Create Date: 2025-10-05 13:43:29.700549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c609c31fee43'
down_revision: Union[str, Sequence[str], None] = '04c77729c223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('public_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=True),
    sa.Column('ends_names', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_venues_public_id'), 'venues', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venues_public_id'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
